version: '3.8'

services:
  backend:
    build: .
    container_name: bloggest-api
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:7-alpine
    container_name: bloggest-redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis-data:/data

volumes:
  redis-data: