name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: SSH and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Connect and Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /var/www/bloggest/APIv2
            git pull origin main
            docker-compose down
            docker system prune -f
            docker-compose build --no-cache
            docker-compose up -d
